### ISSUE TITLE
black table screen

### ISSUE THREAD

**Issue by tjlsmith** [hippich/Bitcoin-Poker-Room#10]
When the table window pops up the whole thing is black. I'm running Ubuntu Maverick and FF 3.6.12

**Comment by hippich** [comment]
hm.. are you talking about betco.in or you are installing your own version?

**Comment by hippich** [comment]
ok. i think you were talking about betco.in. well - looks like bots were overloading server and therefore i turned them off (anyway they were only loosing money =))

**Comment by tjlsmith** [comment]
fixed. Thanks!
