### ISSUE TITLE
Over 10 BTC does not show decimal

### ISSUE THREAD

**Issue by EPiSKiNG** [hippich/Bitcoin-Poker-Room#11]
When the player has more than 10 BTC when seated, it does not show decimals, and this would be nice.

**Comment by DamienBlack** [comment]
I think one decimal place when you have 10-50 chips would be nice. It is weird going from 9.78 to 10 flat.

**Comment by DamienBlack** [comment]
I believe this issue can be fixed at root/static/js/jquery.jpoker.js line 498

if (chips / magnitude < 10) {

The 10 should be able to be changed to a different value, like 20 or 50. All values under that (but above 10) will get one (and only one) decimal place. This will also give one decimal place when you have, for example, 10.2K. Which I think is a good thing.

Please make this change soon. I vote for a value of 30 to 50. Thanks

P.S. if there is a bounty, I'll happily claim it in chips :)
