### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by icecube45** [hippich/Bitcoin-Poker-Room#138]
Hello! after following the fixes for other issues, I'm down to just one

Upon the launch, I receive 

Couldn't instantiate component "Room::Model::PokerNetwork", "argument is not a module name"Compilation failed in require at /usr/local/share/perl/5.14.2/Module/Runtime.pm line 317.
 at /usr/share/perl5/Catalyst/Script/Server.pm line 239

Please, let me know anything I can do to resolve this, as I would love to get this up and running

**Comment by fedaykinofdune** [comment]
I've got the exact same thing, but it's faulting line 20 in Forking.pm. I've been trying to get my head around it, but there doesn't seem to be much info out there, or I'm just not asking the right questions. I'd really like to get this working too.
