### ISSUE TITLE
Can't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [hippich/Bitcoin-Poker-Room#140]
I can't get past this part:
To install all dependencies:
perl Makefile.PL

I get this error:
$ perl Makefile.PL
Can't open perl script "Makefile.PL": No such file or directory

I searched the whole filesystem for a file called Makefile.PL & found copies in:
~/.cpan/build/local-lib-2.000015-_cXY3L/
~/.cpan/build/DBI-1.634-M1fxTG/
~/.cpan/build/ExtUtils-MakeMaker-7.10-NYMytO/

Here I get:
~/.cpan/build/local-lib-2.000015-_cXY3L$ perl Makefile.PL
Warning: prerequisite ExtUtils::MakeMaker 7.00 not found. We have 6.66.
Writing Makefile for local::lib
Writing MYMETA.yml and MYMETA.json
admin@Cassini:~/.cpan/build/local-lib-2.000015-_cXY3L$ sudo make installdeps
make: **\* No rule to make target `installdeps'.  Stop.

And:
~/.cpan/build/DBI-1.634-M1fxTG$ perl Makefile.PL
Can't locate DBI/DBD.pm:   Permission denied at Makefile.PL line 19.
BEGIN failed--compilation aborted at Makefile.PL line 19.
admin@Cassini:~/.cpan/build/DBI-1.634-M1fxTG$

And:
~/.cpan/build/ExtUtils-MakeMaker-7.10-NYMytO$ perl Makefile.PL
Using included version of JSON::PP (2.27203) as it is newer than the installed version (2.27202).
Using included version of Parse::CPAN::Meta (1.4405) as it is newer than the installed version (1.4404).
Using included version of CPAN::Meta::Requirements (2.127) as it is newer than the installed version (2.122).
Using included version of ExtUtils::Manifest (1.65) as it is newer than the installed version (1.63).
Generating a Unix-style Makefile
Writing Makefile for ExtUtils::MakeMaker
Writing MYMETA.yml and MYMETA.json
admin@Cassini:~/.cpan/build/ExtUtils-MakeMaker-7.10-NYMytO$ sudo make installdeps
make: **\* No rule to make target `installdeps'.  Stop.

When I try to continue as if these errors didn't matter, I get to here:
Import new schema:
mysql -u root pythonpokernetwork < schema_dump.sql

And I get:
$ mysql -u root pythonpokernetwork < schema_dump.sql
-bash: schema_dump.sql: No such file or directory

I don't know what to do to get past all this.

Please advise.

Thanks,
-N

**Comment by hippich** [comment]
First of all, very likely it will not work as is, since i did no work on it for few years, and many dependencies changed. So to install it you will have to work throught perl dependencies. May be even change some code to keep it working with newer versions of modules.

Second, Makefile.PL you are look for is right in the root folder of this repository, as well as schema_dump.sql
