### ISSUE TITLE
Account not gaining balance or losing while playing

### ISSUE THREAD

**Issue by Kylemz** [hippich/Bitcoin-Poker-Room#21]
Was recently playing poker in the 0.01 0.02 blinds room, and started off with 1.5 BTC. After playing for a bit, I lost a little bit of BTC and ended up with about 1.00 BTC. After leaving the poker room, I checked my balance and it stated I had 1.49 BTC. I refreshed and to no avail, it stayed the same. Afterwards, I went and played again and ended up with about 16 BTC. I was excited after winning so much that I left the game to secure my winnings. Once checking my balance again, it stated I once again had 1.49 BTC.

Whats going on? 

Please help

Kylemz

**Comment by hippich** [comment]
We are using Bitcent as a unit on tables now. I.e. when you sit at 0.01/0.02 table blinds are 0.01 bitcent / 0.02 bitcent or 0.0001 / 0.0002 BTC. Are you sure you won 16 BTC and not bitcents?

Switch to bitcents happened May 14th.
