### ISSUE TITLE
Linux start-up

### ISSUE THREAD

**Issue by parweb** [hippich/Bitcoin-Poker-Room#26]
I didn't succeed to start the script in my linux computer

I try this :
python script/room_server.pl

output:
File "script/room_server.pl", line 3
    BEGIN {
          ^
SyntaxError: invalid syntax

So what the good command line to test the script ?

**Comment by anisoptera** [comment]
The correct command line is "script/room_server.pl".

**Comment by hippich** [comment]
parweb, .pl - is perl script. so you can't run it with python.

next - this repo used for deployment and do nor provide the whole solution as easy as "perl ./scripts/room_server.pl" yet. Nor auto installer available currently. You need to install Python Poker Network software, configure it, change schema, link to changed poker-engine and poker-network libraries from lib/ppn, configure Room to use PPN database... So this is not straightforward.

If you want just to play poker - welcome to https://betco.in. If you want actively participate in open source project itself - you need to spend quite some time researching it.

**Comment by parweb** [comment]
Thx but i still have few problems :D

now after I typed
script/room_server.pl

ouput:
Can't locate Catalyst/ScriptRunner.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.10.1 /usr/local/share/perl/5.10.1 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.10 /usr/share/perl/5.10 /usr/local/lib/site_perl /usr/local/lib/perl/5.10.0 /usr/local/share/perl/5.10.0 .) at script/room_server.pl line 7.
BEGIN failed--compilation aborted at script/room_server.pl line 7.

**Comment by parweb** [comment]
ok I think I just wait a more "developper" friendly version

**Comment by hippich** [comment]
it is "experienced developer" friendly enough since all bits are there. if you know how to program Perl, how to install Perl modules, how to deal with mysql databases and install system packages, you can work on it. Otherwise - it's not a vocational project phase yet. I am sorry, but trying to start perl script with python is kinda... not very developer way to do things =)

**Comment by parweb** [comment]
Im php developper :D
