### ISSUE TITLE
Need a Pre-Call Delay

### ISSUE THREAD

**Issue by DamienBlack** [hippich/Bitcoin-Poker-Room#27]
The check box for calling a specific amount, for example, "call .05" changes instantly when someone raises. This has caused me problems when I mean to click "call .05", but then the person right before me raises something, I accidentally click, and don't have time to unclick before money my is put in. I think that when someone raises the button should be greyed out for a second before you can auto-call the new amount.

This has been one of my biggest problems while playing here. I'm afraid to click the auto-call button.

EDIT: The same needs to be done with the raise button.

**Comment by hippich** [comment]
This should be implemented also for buttons like this:

1) Players click on a action button
2) Button grey-out or change look to "pressed" state for 1-2 seconds
3) After 1-2 seconds delay action fired and action buttons disappear.
4) During these 1-2 seconds delay action should be undoable by clicking again on same action button.

**Comment by frolic** [comment]
I don't have the means to test this (no Bitcoins), but I think the trouble described here is pre-click, not post-click.

I'm going to submit a pull request with a proposed fix based on my understanding of the issue without testing in hopes I can claim that Bitcoin bounty and help out a bit more with the other issues.

**Comment by hippich** [comment]
Hey, thanx for pull request. Although I wanted to make it slightly more complex - expand this to action buttons as well. Please read my seconds comment and let me know if you will be able to implement it as well?

**Comment by frolic** [comment]
No problem. Can you drop a small amount of chips into my account (username: SHA1) or provide me with a test account so that I can interact with the UI? I'm coding blind here...

**Comment by hippich** [comment]
I have better solution - I have complete virtualbox machine with everything installed and ready to run. Send me email to pavel@yepcorp.com - I will upload it online and send you a link to it.

**Comment by frolic** [comment]
I updated my pull request with an untested theoretical fix. Feel free to give it a whirl while that Virtualbox file is being uploaded.
