### ISSUE TITLE
Muck order seems wrong

### ISSUE THREAD

**Issue by DamienBlack** [hippich/Bitcoin-Poker-Room#31]
The order of that people are showing their hands seems wrong. From http://en.wikipedia.org/wiki/Showdown_%28poker%29

"Robert's Rules of Poker state that the last player to take aggressive action by a bet or raise is the first to show the hand—unless everyone checks (or is all-in) on the last round of betting, then the first player to the left of the dealer button is the first to show the hand."

Currently it seems like the person left of the dealer always starts. This is wrong.

**Comment by anisoptera** [comment]
Not only is the muck order correct as of commit d14340e49419f8fd9fed , but the quoted section of Robert's Rules of Poker is in the commit message.
