### ISSUE TITLE
'dead' blinds off by factor of 100

### ISSUE THREAD

**Issue by dooglus** [hippich/Bitcoin-Poker-Room#32]
When someone pays small and big blinds at the same time, the dealer chat shows:

  Dealer: player pays 1 blind and 50 dead

It should be:

  Dealer: player pays 1 blind and 0.50 dead

This is in a 0.50/1.00 game.

In 0.05/0.10 it says:

  Dealer: player pays 0.10 blind and 5 dead

and so on.

**Comment by anisoptera** [comment]
Fixed in commit ddd7e3abb3b4f798b262.
