### ISSUE TITLE
.10/.25 has .12 small blinds

### ISSUE THREAD

**Issue by dooglus** [hippich/Bitcoin-Poker-Room#37]
Cerrt 1 is a .10-.25-no-limit holdem table, but:

Dealer: DJHeRobot pays 0.12 blind
Dealer: polymath pays 0.25 blind

the blinds are 12 and 25, not 10 and 25.

**Comment by DamienBlack** [comment]
I think it is common to get as close to one half as you can... but I suppose it is mislabeled in the lobby.

**Comment by dooglus** [comment]
I know PokerStars has 2c/5c and 10c/25c games, and all their other games have BB = 2 SB.

I don't care whether the blinds are .12/.25 or .10/.25, but the blinds should match the description.

**Comment by hippich** [comment]
hm.. it's just configuration issue. i will change it to .12 .25 blinds once nobody will be in the room.
