### ISSUE TITLE
server crash?

### ISSUE THREAD

**Issue by dooglus** [hippich/Bitcoin-Poker-Room#47]
At approx. Sun Jun 12 15:10:00 PDT 2011 all the tables froze, and when I reloaded, they were empty.  People came back one by one, saying they had experienced the same.

Maybe it was just a server reboot or something, but maybe there's something in a logfile that could help diagnose this if it was caused by a bug.

**Comment by DamienBlack** [comment]
I can confirm this, I refreshed several times and and first everyone was folding as they timed out (but I could not see who actually had the action). Then I refreshed and no one was at the table. This was Instis 4.

EDIT: it did the same thing again about 15 minutes later

And again at Ingwskel 4 a few hours later.. and again... this is definitely a recurring problem.

**Comment by dooglus** [comment]
I was on the same table.  I can't say what happened on the other tables, but when I refreshed the table list, there was no more than 1 person at any table.

**Comment by dooglus** [comment]
"Comment and close" doesn't mean "close tab" I see.  Live and learn...

**Comment by hippich** [comment]
Yeah, dooglus right. It crashed due small mistype - https://github.com/hippich/Bitcoin-Poker-Room/commit/c8b0edf5a4c8df2e6496fd36f2c98f81393503f3 - fixed in code, but need to restart server. Either it will crash itself again or people leave tables and I will restart it manually.
