### ISSUE TITLE
I paid BB 4 hands in a row

### ISSUE THREAD

**Issue by sundayhustler** [hippich/Bitcoin-Poker-Room#52]
On a .10/.25 NLH table, during hands 163920-163923, I was sitting in seat 2, with a live player sitting to my right in seat 1, and a player to my left in seat 3, who was sitting out.  Player in seat 3 had the button, so player 1 was SB and I (player 2) was BB.  For four straight hands, this same scenario repeated.  The button did not move, player 1 was always SB, and I was always BB.

In hand 163924, things returned to normal when player 3 joined back into the game.  The button moved to player 1, I became SB, and player 3 became BB.

**Comment by anisoptera** [comment]
Commit d03c5b2427b51c5a2aef probably fixed this, since the client will now explicitly handle blind requests. I'll inspect the hand histories and reopen if I think there's some deeper issue.

**Comment by anisoptera** [comment]
Looking at these hand histories, I don't have enough data to track this down. I've opened issue #71 for that problem. As for this, I'm closing this out until we get another report.
