### ISSUE TITLE
inc/ mistakenly committed

### ISSUE THREAD

**Issue by shadowcat-mst** [hippich/Bitcoin-Poker-Room#55]
inc/ should never be in the repository, only the dist.

We just had a user in #catalyst who'd installed Catalyst::Devel but was getting random errors because your inc/ in the repo is incomplete.

It shouldn't be there at all.

If people want to develop your software, they should check out the repo, install Catalyst::Devel, and run Makefile.PL to populate inc/

If people want to install your software, they should do so from a 'make dist' tarball you've provided.

Hope that clears things up.

-- mst

**Comment by hippich** [comment]
Wow. Mst! Thanks for your input. Yeah, the whole thing is very amateurish. I will read more about it and correct it.
