### ISSUE TITLE
chat box lets you type more than it accepts

### ISSUE THREAD

**Issue by dooglus** [hippich/Bitcoin-Poker-Room#58]
It's possible to type a long sentence into the chat box, but only a certain number of characters are used in the message you send.  After that the rest are lost.

For example:

PhilIvey: well i dont know what to say i guess im just sick of drama thats what benig from a small town tends to bring.umm i love music ma

and:

dooglus: It's possible to type a long sentence into the chat box, but only a certain number of characters are used in the message you sen

ie. only 128 characters are used.

We should either allow longer messages, or limit the amount that can be typed.  Silently throwing away text is annoying for the user.

**Comment by dooglus** [comment]
https://github.com/dooglus/Bitcoin-Poker-Room/commit/21678c247830e06d9675b2d7c89c372a3815ea04 should fix the problem, but I don't know how to make a pull request for just that commit.

**Comment by anisoptera** [comment]
Applied commit 5d8de9d to fix this.

In the future we may look into allowing larger messages.
