### ISSUE TITLE
decimal raise bug still exists after turn card at 0.02 chip bb ring table

### ISSUE THREAD

**Issue by hitego** [hippich/Bitcoin-Poker-Room#72]
I was trying to bet much more on the turn and river, but the raise button would not respond until I had changed my raise to have no significant digits after the decimal value (tenths of a chip). This is a bad bug: it drives away new players who want to play at the lowest limit because they might think the software is not working. I saw hippich working on this issue on a 0.04 bb table and he mentioned the decimal problem, it was fixed at 0.04 but is still present at 0.02.

Betco.in Game #240234: holdem .01-.02-no-limit 2011-07-11T00:09:13 
Table 'N/A' 10-max Seat #3 is the button
Seat 1: cAPSLOCK ($1.96 in chips)
Seat 2: hitego ($2.04 in chips)
cAPSLOCK: posts small blind $0.01 
hitego: posts big blind $0.02 
**\* HOLE CARDS ***
Dealt to hitego [6d 8h]
cAPSLOCK: bets $0.04 
hitego: bets $0.17 
cAPSLOCK: calls $0.13 
**\* FLOP **\* [5c 9d 7d]
hitego: bets $0.11 
cAPSLOCK: calls $0.11 
**\* TURN **\* [5c 9d 7d 5d]
hitego: bets $0.20 
cAPSLOCK: calls $0.20 
**\* RIVER **\* [5c 9d 7d 5d Kh]
hitego: bets $0.40 
cAPSLOCK: calls $0.40 
**\* SHOW DOWN ***
cAPSLOCK: shows [Kc 9c]
hitego: shows [6d 8h]
hitego collected 1.74 from pot
**\* SUMMARY ***
Total pot $1.76 | Rake $0.02
Board [5c 9d 7d 5d Kh]
Seat 1: cAPSLOCK showed [Kc Kh 9c 9d 7d]
Seat 2: hitego showed [9d 8h 7d 6d 5c] and won ($1.74) with Straight

**Comment by hitego** [comment]
Actually after some further playing, it seems that the smallest resolution of the bet has to be at 1 big blind. If there are single chip cents in the bet there are problems. A bet of 0.07 does not work, while a bet of 0.06 at 0.02 big blinds seems to work.

**Comment by hitego** [comment]
playing 0.04 bb full ring again people are reporting raise problems:
theman: takes longer also cause the 1/2, 3/4 pot buttons dont work to raise
theman: like.. you cant open for .15 but you can for .10

**Comment by hippich** [comment]
Fixed there - https://github.com/hippich/Bitcoin-Poker-Room/commit/1cb72d7f23e43ea0441fe46989846f6e9edddcf2
