### ISSUE TITLE
possible collusion

### ISSUE THREAD

**Issue by hitego** [hippich/Bitcoin-Poker-Room#79]
I've been sitting at a 3 handed table for about an hour, and on the final hand both of the opponents I'm playing sit out at the same time after this hand, I pressed the sitout button myself before I open raised this hand. Can someone check the ip addresses of the two players I was playing, and see if the addresses play together regularly?

Betco.in Game #262378: holdem .50-1-no-limit 2011-07-17T12:22:23 
Table 'N/A' 10-max Seat #3 is the button
Seat 1: bringpowellms ($199.35 in chips)
Seat 2: hitego ($147.55 in chips)
Seat 3: comradehls ($142.16 in chips)
comradehls: posts small blind $0.50 
bringpowellms: posts big blind $1.00 
**\* HOLE CARDS ***
Dealt to hitego [xxxxx]
hitego: bets $2.00 
comradehls: calls $1.50 
bringpowellms: folds
**\* FLOP **\* [8c Tc 5c]
comradehls: bets $3.00 
hitego: calls $3.00 
**\* TURN **\* [8c Tc 5c 6d]
comradehls: bets $11.00 
hitego: calls $11.00 
**\* RIVER **\* [8c Tc 5c 6d Kc]
comradehls: bets $33.00 
hitego: folds
comradehls collected 65.67 from pot
**\* SUMMARY ***
Total pot $66.00 | Rake $0.33
Board [8c Tc 5c 6d Kc]
Seat 1: bringpowellms folded
Seat 2: hitego folded
Seat 3: comradehls won ($65.67) (Everybody else folded)

**Comment by hippich** [comment]
bringpowellms is old player and pretty good one. comradehis has history of playing with other players. they have different IP addresses, OS/Browser finger prints. They are just pretty aggressive players.
