### ISSUE TITLE
Service Temporarily Unavailable 

### ISSUE THREAD

**Issue by smickles** [hippich/Bitcoin-Poker-Room#94]
Hi all, I'm trying to get this running on my home server. 
The problem is likely some aspect of my own ignorance.
If this is the wrong location for such a help request, please redirect me to the proper location.

I followed the README instructions and it seemed to all go fine, no problems, until the last line. 

```
Navigate to http://room/ or whatever domain you created for this project.
```

I've tried the domain which I've created for this project, http://room/, localhost, and several others which I thought may be related.
In all cases I come up with "Service Temporarily Unavailable"

Any help will be appreciated.

**Comment by hippich** [comment]
what is shown when you run "./script/room_server.pl -r -f "?

**Comment by smickles** [comment]
Thank you for the prompt response. 
Upon examination of the output I realized I did not have several modules installed.

After the installation of these modules I was able run the script as well as navigate to the http://room/ equivalent and able to create a user and login, however attempting to enter a table would bring up the window for the table with a connection error.

```
 {"xhr":"{\"status\":404,\"responseText\":\"Page not found\",\"readyState\":4}","status":"error","url":"/POKER_REST","error":"Not Found"}attempt to stringify failed with exception: ReferenceError: printStackTrace is not defined
```

**Comment by smickles** [comment]
oops, didn't mean to close, but can't seem to reopen...

**Comment by hippich** [comment]
Please post content of /etc/apache2/sites-available/room.conf

**Comment by smickles** [comment]
```
 <VirtualHost *:80>
   ServerName room

   <Proxy *>
     Order deny,allow
     Allow from all
   </Proxy>
   ProxyPass /POKER_REST http://localhost:19384/POKER_REST retry=1
   ProxyPass / http://localhost:3000/ retry=1
 </VirtualHost>
```

**Comment by hippich** [comment]
you mentioned "http://room/", what exact url you enter into browser url bar?

**Comment by smickles** [comment]
I am using pickles:3000 (pickles is the name of the local machine)

**Comment by hippich** [comment]
make sure to update ServerName with "pickles" and open http://pickles/ (no 3000 port)

**Comment by smickles** [comment]
All seems well, Thanks for your help.
